# Generated by Django 3.2.13 on 2023-03-04 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contatcs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_loc_ru', models.CharField(max_length=255)),
                ('text_loc_en', models.CharField(max_length=255)),
                ('text_loc2_en', models.CharField(max_length=255)),
                ('text_loc2_ru', models.CharField(max_length=255)),
                ('tel1', models.CharField(max_length=255)),
                ('tel2', models.CharField(max_length=255)),
                ('tel3', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
