# Generated by Django 3.2.13 on 2023-03-04 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contatcs',
            new_name='Contacts',
        ),
    ]
