# Generated by Django 3.2.13 on 2023-02-28 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0002_auto_20230227_1008'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255)),
                ('quantity', models.CharField(max_length=255)),
                ('customer', models.CharField(max_length=255)),
                ('directions', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='directions', to='catalogue.main_directions')),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_name', to='catalogue.product_card')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
