# Generated by Django 3.2.13 on 2023-03-11 16:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='title_ru',
        ),
        migrations.AddField(
            model_name='delivery',
            name='delivery_time',
            field=models.DateField(default=datetime.datetime(2023, 3, 11, 16, 37, 58, 521069, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
