# Generated by Django 3.2.13 on 2023-03-12 08:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_auto_20230311_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='customer_ru',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='delivery',
            name='quantity_ru',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
