# Generated by Django 3.2.13 on 2023-03-25 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_auto_20230312_0834'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='delivery',
            options={'ordering': ['id']},
        ),
    ]
