# Generated by Django 3.2.13 on 2023-03-04 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0002_auto_20230303_1044'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='main_page',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='document',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='document', to='main_page.main_page'),
        ),
    ]
