# Generated by Django 3.2.13 on 2023-03-04 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0003_auto_20230304_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main_page',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
