# Generated by Django 3.2.13 on 2023-03-04 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0004_alter_main_page_title_en'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document', to='main_page.main_page'),
        ),
        migrations.AlterField(
            model_name='main_page',
            name='title_en',
            field=models.CharField(max_length=255),
        ),
    ]
