# Generated by Django 3.2.13 on 2023-02-24 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255)),
                ('post_time', models.DateField()),
                ('image', models.ImageField(upload_to='news_images/main_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Detail_page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255)),
                ('reading_time_ru', models.CharField(max_length=255)),
                ('reading_time_en', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='news_images/background_images/')),
                ('text_en', models.TextField()),
                ('text_ru', models.TextField()),
                ('publication_author_en', models.CharField(max_length=50)),
                ('publication_author_ru', models.CharField(max_length=50)),
                ('detailpage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detailpage', to='news.news')),
            ],
        ),
    ]
