# Generated by Django 3.2.13 on 2023-03-04 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20230227_0953'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detail_page',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['id']},
        ),
    ]
