# Generated by Django 3.2.13 on 2023-02-27 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Main_Directions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='catalogue/direction_images/')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Product_card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255)),
                ('producer_ru', models.CharField(max_length=255)),
                ('producer_en', models.CharField(max_length=255)),
                ('model_en', models.CharField(max_length=255)),
                ('model_ru', models.CharField(max_length=255)),
                ('diameter_en', models.CharField(max_length=255)),
                ('diameter_ru', models.CharField(max_length=255)),
                ('pressure_ru', models.CharField(max_length=255)),
                ('pressure_en', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255)),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subcategory', to='catalogue.category')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Product_images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='catalogue/product_images/')),
                ('product_images', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_images', to='catalogue.product_card')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Product_detailpage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='catalogue/product_logo/')),
                ('title_ru', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255)),
                ('text_en', models.TextField()),
                ('text_ru', models.TextField()),
                ('product_detailpage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_detailpage', to='catalogue.product_card')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='product_card',
            name='product_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_card', to='catalogue.subcategory'),
        ),
        migrations.CreateModel(
            name='Characteristics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255)),
                ('value_ru', models.CharField(max_length=255)),
                ('value_en', models.CharField(max_length=255)),
                ('characteristics', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='characteristics', to='catalogue.product_detailpage')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='category',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='category', to='catalogue.main_directions'),
        ),
    ]
