# Generated by Django 3.2.13 on 2023-02-27 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_detailpage',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='product_detailpage',
            name='title_ru',
        ),
    ]
