# Generated by Django 3.2.13 on 2023-03-03 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_auto_20230227_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_card',
            name='product_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_card', to='catalogue.category'),
        ),
        migrations.DeleteModel(
            name='Subcategory',
        ),
    ]
