# Generated by Django 3.2.13 on 2023-03-03 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_auto_20230303_0521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_images',
            name='product_images',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_images', to='catalogue.product_detailpage'),
        ),
    ]
