# Generated by Django 3.2.13 on 2023-03-04 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0005_auto_20230304_1727'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='main_directions',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='product_card',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='product_detailpage',
            options={'ordering': ['id']},
        ),
    ]
