# Generated by Django 3.2.13 on 2023-03-25 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0006_auto_20230304_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_detailpage',
            name='title_en',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product_detailpage',
            name='title_ru',
            field=models.CharField(default='text', max_length=255),
            preserve_default=False,
        ),
    ]
