# Generated by Django 3.2.13 on 2023-02-27 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupation_name_ru', models.CharField(max_length=255)),
                ('occupation_name_en', models.CharField(max_length=255)),
                ('duties_text_ru', models.TextField()),
                ('duties_text_en', models.TextField()),
                ('requirements_text_ru', models.TextField()),
                ('requirements_text_en', models.TextField()),
                ('condition_text_ru', models.TextField()),
                ('condition_text_en', models.TextField()),
                ('contacts_text_ru', models.TextField()),
                ('contacts_text_en', models.TextField()),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
