# Generated by Django 3.2.13 on 2023-02-28 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0002_jobs_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='icon',
            field=models.ImageField(upload_to='jobs/icon/'),
        ),
    ]
