# Generated by Django 3.2.13 on 2023-03-04 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0004_alter_jobs_icon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobs',
            options={'ordering': ['id']},
        ),
    ]
