# Generated by Django 3.2.13 on 2023-03-06 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0005_alter_jobs_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs_title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=255)),
                ('title_ru', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='jobs',
            name='condition_text_en',
        ),
        migrations.RemoveField(
            model_name='jobs',
            name='condition_text_ru',
        ),
        migrations.RemoveField(
            model_name='jobs',
            name='contacts_text_en',
        ),
        migrations.RemoveField(
            model_name='jobs',
            name='contacts_text_ru',
        ),
        migrations.RemoveField(
            model_name='jobs',
            name='duties_text_en',
        ),
        migrations.RemoveField(
            model_name='jobs',
            name='duties_text_ru',
        ),
        migrations.RemoveField(
            model_name='jobs',
            name='requirements_text_en',
        ),
        migrations.RemoveField(
            model_name='jobs',
            name='requirements_text_ru',
        ),
        migrations.CreateModel(
            name='Jobs_title_des',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_en', models.CharField(max_length=255)),
                ('text_ru', models.CharField(max_length=255)),
                ('jobs_title_des', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs_title_des', to='vacancies.jobs_title')),
            ],
        ),
        migrations.AddField(
            model_name='jobs_title',
            name='jobs_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs_title', to='vacancies.jobs'),
        ),
    ]
